spring:
  datasource:
    url: jdbc:mysql://@mysql_ip@:@mysql_port@/clouddb01?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: @mysql_username@
    password: @mysql_password@
