spring:
  datasource:
    url: jdbc:mysql://@mysql_ip@:@mysql_port@/clouddb01?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: @mysql_username@
    password: @mysql_password@
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
logging:
  level:
    com.springboot.cache.mapper: debug
#debug: true
